### ISSUE TITLE
How to get index quote

### ISSUE THREAD

**Issue by il023109** [anilshanbhag/RobinhoodShell#10]
like $SPX

**Comment by mchauhan3** [comment]
I don't know if that's a thing in Robinhood

**Comment by anilshanbhag** [comment]
You can check this with stock equivalents like $SPY, $QQQ, etc

**Comment by anilshanbhag** [comment]
@mchauhan3 drop me an email sometime anilashanbhag @ gmail .com

**Comment by mchauhan3** [comment]
@anilshanbhag Sent you a mail from mhchauhan3 @ gmail . com
