### ISSUE TITLE
Way to pass parameters?

### ISSUE THREAD

**Issue by cole-seph** [anilshanbhag/RobinhoodShell#13]
Are parameters currently supported in any fashion? (Aside from simply changing the shell code)
Would be really nice to call this from another script and work in my own automation from there
Ex:
./shell.py -l

**Comment by cfarthingale** [comment]
I am interested in the answer to this question as well as the option to pass parameters in a script like this could be useful in monitoring various RH account information using bash/conky. -Thank you.

**Comment by anilshanbhag** [comment]
There is no way to do it currently. However, it shouldn't be hard to do it - you need to pass the command line arg to Command. 
Feel free to submit a pull request for it.
