### ISSUE TITLE
Work with cryptocurrency trading

### ISSUE THREAD

**Issue by madtrap347** [anilshanbhag/RobinhoodShell#15]
Hello was wondering if this works with cryptocurrency trading in RH? RH doesnt offer stop loss or stop buys for cryptocurrencies

**Comment by riscphree** [comment]
No plans, see: https://github.com/anilshanbhag/RobinhoodShell/issues/4

**Comment by amarotica** [comment]
You said it was not implemented but is functional in #4 Can you give an example of how we can do crypto using your shell? Thanks

**Comment by anilshanbhag** [comment]
I do not have crypto enabled on my Robinhood, as a result I am not sure how to go forward with implementing crypto.
