### ISSUE TITLE
error with install

### ISSUE THREAD

**Issue by shummer6** [anilshanbhag/RobinhoodShell#16]
I've previously installed everything without issue. My machine got a clean wipe and now as I try to reinstall this I get this error.

`squinton-ml:RobinhoodShell shaunquinton$ sudo pip install -r requirements.txt
Password:
The directory '/Users/shaunquinton/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/shaunquinton/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting beautifultable==0.3.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/74/a8/1b183b85dfe7434f4a99477b8c8a6b2bf6f2cdd6b4b113267d25a4ba036e/beautifultable-0.3.0.tar.gz
Collecting enum==0.4.6 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/0c/4e/1ea357e7783c756bb579333c1e4a026fb331371ee771f616ffedc781e531/enum-0.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 9, in <module>
        import re
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 143, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-ox7486a5/enum/`

I've tried the suggestions in the error messaging, but have not been able to resolve the issue. Is anyone else getting this error?

**Comment by anilshanbhag** [comment]
Try running with python 2.7. I think the error is because of python 3.
