### ISSUE TITLE
Include more parameters in list table

### ISSUE THREAD

**Issue by Nexuist** [anilshanbhag/RobinhoodShell#19]
Currently the list table includes symbol, current price, quantity, and total equity. It would be very useful if you could also include things like % change, today's return, and total return, as this helps me better gauge how well every pick is going. I'm not sure how difficult this would be, depending on if the data is included in the request you make, but I think it's worth putting it in.

I might be able to help with this if you'd like. I'd just need to know where I could find the data I'm looking for within the API.

Thanks!

**Comment by anilshanbhag** [comment]
Take a look at code around https://github.com/anilshanbhag/RobinhoodShell/blob/master/shell.py#L97
You can see all the data you need is likely there. Just add the necessary entries as additional columns.
