### ISSUE TITLE
Buy command orders wrong stock

### ISSUE THREAD

**Issue by freddawes** [anilshanbhag/RobinhoodShell#2]
Buy command orders the wrong stock symbol.

Buy command examples:
b NX 1 17.10
b LIVE 1 12.85

Resulting orders:
NXPI
LYV

The first example results in ordering of stocks with a different symbol that contains letters from the first symbol, but the second example is a stock that has a completely different symbol but the company has the same name.  The RH API URLs in instrument.data appear to be correct.  Interestingly, the resulting orders are the first search results on the list of stocks that appear when using the original app interface.

**Comment by anilshanbhag** [comment]
Thats strange, I see the problem:
`q NX` returns the right stock
`b NX 1 17.2` returns the wrong stock

**Comment by freddawes** [comment]
Thanks for getting back to me, this is very useful code that I use all the time.

**Comment by anilshanbhag** [comment]
Will fix it later tonight or tomorrow. Thanks for notifying.

**Comment by anilshanbhag** [comment]
Should be fixed now. The issue was querying instruments returns a list of results; need to check to find the right one among the results.

**Comment by freddawes** [comment]
Thanks.
