### ISSUE TITLE
object has no attribute 'upper'

### ISSUE THREAD

**Issue by HMSS013** [anilshanbhag/RobinhoodShell#20]
this error has begun occurring when using the 'l' list all option:

Traceback (most recent call last):
  File "./shell.py", line 565, in <module>
    RobinhoodShell().cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./shell.py", line 86, in do_l
    raw_data = self.trader.quotes_data(symbols)
  File "/home/HMSS013/.dropbox-shared/Dropbox/Public/Market Service/Shell/Robinhood.py", line 257, in quotes_data
    raise NameError('Invalid Symbols: ' + ",".join(stocks)).upper() #TODO: custom exception
AttributeError: 'exceptions.NameError' object has no attribute 'upper'

**Comment by anilshanbhag** [comment]
Looks like the Robinhood API has changed, will take a look at it later today.

**Comment by anilshanbhag** [comment]
Should be fixed now

**Comment by HMSS013** [comment]
wow, that was fast! thanks for patching that up Anil.

...mind if i PayPal you a few beers?

-Alex

On Jan 15, 2019 9:50 AM, "Anil Shanbhag" <notifications@github.com> wrote:

Closed #20 <https://github.com/anilshanbhag/RobinhoodShell/issues/20>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/anilshanbhag/RobinhoodShell/issues/20#event-2075310353>,
or mute the thread

**Comment by anilshanbhag** [comment]
Haha sure anils@mit.edu :)
