### ISSUE TITLE
Exceptions.nameerror object has no attribute upper

### ISSUE THREAD

**Issue by austinvlewis** [anilshanbhag/RobinhoodShell#21]
raise NameError('Invalid Symbols: ' + ",".join(stocks)).upper() #TODO: custom exception
AttributeError: 'exceptions.NameError' object has no attribute 'upper'

Saw where this was an issue previously. Am still running into it though any suggestions? Occurs when I try to view my portfolio

**Comment by anilshanbhag** [comment]
Fixed this issue.
