### ISSUE TITLE
All Logins Fail As Of Today

### ISSUE THREAD

**Issue by HMSS013** [anilshanbhag/RobinhoodShell#22]
Reset a few devices I had this afternoon and all at once they were unable to log back in... several accounts... credentials are all correct.

$ ./Shell/shell.py 
Traceback (most recent call last):
  File "./Shell/shell.py", line 564, in <module>
    RobinhoodShell().cmdloop()
  File "./Shell/shell.py", line 37, in __init__
    self.trader.login(username=USERNAME, password=PASSWORD)
  File "/home/Z8/ETF/Shell/Robinhood.py", line 136, in login
    raise RH_exception.LoginFailed()
AttributeError: 'module' object has no attribute 'LoginFailed'

**Comment by anilshanbhag** [comment]
Yes, Robinhood seems to have added an additional layer of security where in you need to verify the device through email/text. Will see if we can add something similar to the shell.

**Comment by klepsydra** [comment]
Reliant on this as well! Two related threads I've been following are https://github.com/westonplatter/fast_arrow/issues/85 and
https://github.com/Jamonek/Robinhood/issues/176#issuecomment-489291269
Wish I could help fix RobinhoodShell--and I've managed to induce an email auth code using https://github.com/aamazie/Robinhood/blob/master/Robinhood/Robinhood.py and my own Gmail imap realtime fetcher, but don't know where to take it from there (in code).

**Comment by klepsydra** [comment]
Hey @anilshanbhag , how can I modify RobinhoodShell's login mechanism to require, besides username and password, either a 6-digit QR code offered when 2FA gets enabled, email verification code, or even an already-authenticated token acquired through other means (from another project that solved this)?

If device_id is also required, I can also obtain that elsewhere and provide that to RobinhoodShell login inputs.
