### ISSUE TITLE
Unable to login using Windows7 64bit

### ISSUE THREAD

**Issue by Jstlrng** [anilshanbhag/RobinhoodShell#29]
Any ideas what this means? I receive the sms code on my device, I then type it in the command prompt, but I then I get a login error after pressing enter. I am a Windows expert, but unfortunately not in Python. Whatever help you can provide would be greatly appreciated.

![RobinhoodLoginError](https://user-images.githubusercontent.com/55675206/65397983-3f5c2080-dd82-11e9-9a71-51582a939e79.jpg)

**Comment by TheCrockett** [comment]
Off the bat, it looks like you're somehow ending up with double slashes in the URL.

Probably a windows/linux thing



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by anilshanbhag** [comment]
Hmm, not sure what the issue is. On line 200, you should be getting a challenge id. That is not coming through from Robinhood, i am unable to replicate the issue.

**Comment by Jstlrng** [comment]
I modified the Robinhood.py line 200 by removing a slash as shown in the below figure, and now I am getting a different error message.

![image](https://user-images.githubusercontent.com/55675206/65482066-d1892500-de65-11e9-8b83-82a8bda9c80d.png)

![image](https://user-images.githubusercontent.com/55675206/65482060-cafaad80-de65-11e9-9a2a-da126c5c59fd.png)

**Comment by TheCrockett** [comment]
I'm not at home, but that seems like an odd spot for the var to be.

If its right (might be).... them maybe challenge_id isnt defined (since its substituting nothing)



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by Jstlrng** [comment]
hi guys, any new thoughts about this? Thanks
