### ISSUE TITLE
Buy command cannot find stock but quote command can

### ISSUE THREAD

**Issue by freddawes** [anilshanbhag/RobinhoodShell#3]
Buy command returns stock not found but the price is accessible through q command and stock is purchasible via app interface.

Buy command examples:
b AUTO 1 15.00
Stock not found

q AUTO
AUTO: $15.00

=======

EDIT: Symbol not visible through app interface, please delete this issue.  Sorry about that.

**Comment by anilshanbhag** [comment]
Interesting, will take a look later today.

**Comment by freddawes** [comment]
Sorry, please delete, stock is not accessible through app interface.  My mistake.
