### ISSUE TITLE
how to get option quote?

### ISSUE THREAD

**Issue by il023109** [anilshanbhag/RobinhoodShell#9]
I can use "q SPY", but how can I do "q SPY call 270 6/29".

thanks.

**Comment by anilshanbhag** [comment]
it isn't implemented - would appreciate a pull request

**Comment by mchauhan3** [comment]
I can work on it

**Comment by il023109** [comment]
I can help for testing.

But how can you reverse engineering the symbol format for quote options? from sniff robinhood app?
I thought it is all HTTPS.

**Comment by mchauhan3** [comment]
No, you can use Firefox and Robinhood web

**Comment by il023109** [comment]
I see.

I thought robinhood web does not support option quote yet though.

**Comment by mchauhan3** [comment]
Yeah but you can figure out the endpoints and poke around

**Comment by il023109** [comment]
:)

Nice.

**Comment by anilshanbhag** [comment]
Fixed by #11

**Comment by il023109** [comment]
works great
